const connection=require('../config/databaseConfig');
const resultUtils=require('../utils/resultUtils');
const sqlTmpl=require('../utils/crudUtils');

module.exports={
    //查询全部用户信息或根据条件进行查询
    getUserList:(req,res,next)=>{
        sqlTmpl.querySql('test_person_info',req.query,(sql)=>{
            if(sql===""){
                res.send(resultUtils.queryFailureResult(0,"传参格式错误"));
            }else{
                connection(sql,(err,result,fields)=>{
                    if(err){
                        res.send(resultUtils.queryFailureResult(0,`查询失败,${err.sqlMessage}`));
                    }else{
                        let rows=JSON.parse(JSON.stringify(result));
                        res.send(resultUtils.querySuccessResult(1,"查询成功",rows,rows.length));
                    }
                })
            }
        });
    },
    //新增用户信息
    addUser:(req,res,next)=>{
        sqlTmpl.addSql('test_person_info',req.body,(sql)=>{
            if(sql===""){
                res.send(resultUtils.operateFailureResult(0,"传参格式错误"));
            }else{
                connection(sql,(err,result,fields)=>{
                    if(err){
                        res.send(resultUtils.operateFailureResult(0,`新增失败,${err.sqlMessage}`));
                    }else{
                        res.send(resultUtils.operateSuccessResult(1,"新增成功",null));
                    }
                })
            }
        });
    },
    //更新用户信息
    editUser:(req,res,next)=>{
        sqlTmpl.updateSql('test_person_info',req.body,(sql)=>{
            if(sql===""){
                res.send(resultUtils.operateFailureResult(0,"传参格式错误"));
            }else{
                connection(sql,(err,result,fields)=>{
                    if(err){
                        res.send(resultUtils.operateFailureResult(0,`编辑失败,${err.sqlMessage}`));
                    }else{
                        res.send(resultUtils.operateSuccessResult(1,"编辑成功",null));
                    }
                })
            }
        });
    },
    //删除用户信息
    deleteUser:(req,res,next)=>{
        sqlTmpl.deleteSql('test_person_info',req.body,(sql)=>{
            if(sql===""){
                res.send(resultUtils.operateFailureResult(0,"传参格式错误"));
            }else{
                connection(sql,(err,result,fields)=>{
                    if(err){
                        res.send(resultUtils.operateFailureResult(0,`删除失败,${err.sqlMessage}`));
                    }else{
                        res.send(resultUtils.operateSuccessResult(1,"删除成功",null));
                    }
                })
            }
        });
    }
}