on:
  push:
    branches: # 当推送分支时
      - master
env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}  #新建的TOKEN
  aliyun_docker_username: ${{secrets.aliyun_docker_username}}
  aliyun_docker_password: ${{secrets.aliyun_docker_password}}
jobs:
  #构建安装依赖，构建文件
  build-production: 
    runs-on: ubuntu-latest
    steps:
			- name: checkout 
				uses: actions/checkout@v2
			# 安装使用 node:12
			- name: setup Node.js 10.x
				uses: actions/setup-node@v1
				with:
					node-version: '10.x'
			# 安装依赖
			- name: Install Dependencies And Build 
				run: | 
					npm install
				env:
					CI: true
			# 生成镜像
			- name: Build Docker image
				run: |
					docker login --username=唔通叫家家 --password=Aa19961023. registry.cn-shenzhen.aliyuncs.com 
					docker build -f ../../Dockerfile -t registry.cn-shenzhen.aliyuncs.com/wutongjiaojiajia/wood-judge-back-end:mater .
					docker push registry.cn-shenzhen.aliyuncs.com/wutongjiaojiajia/wood-judge-back-end:mater