name: MYCI
on:
    # 发生在推送事件时
    push:
        # 只有当推送代码到mater分支才执行
        branches:
            - master
        # 只有当serive文件发生变动才执行
        # path:
        #     - service/*
jobs:
    job1:
        # 跑在哪个系统上
        runs-on: unbuntu-latest
        steps:
            # 官方提供的actions复制代码到Github服务器上
            - name: Copy Code To Github Server
              uses: actions/checkout@v2
            # 配置Node.js环境
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              # 指定Node.js版本
              with:
                node-version: '10.x'
            - run: |
                npm install
                npm run build --if-present
                npm test --if-present
            - name: Test Secrets
              run: |
                echo ${{ secrets.ALIYUN_DOCKER_USERNAME }}
                echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

    job2:
        # 需要job1完成才执行job2
        needs: job1
        runs-on: unbuntu-latest
        # 运行在docker容器内
        container:
            image: node:8
        steps:
            - uses: actions/checkout@v2
            # 输出
            - run: |
            node -v # v8.16.1
    job3:
        needs: job2
        runs-on: unbuntu-latest
        service:
            nginx:
                image: nginx
                ports:
                    - 8080:80   #映射端口
                env:
                    NGINX_PORT: 80  #指定nginx端口为80
        steps:
            - uses: actions/checkout@v2
            # 输出
            - run: |
                curl localhost:8080 # 打印出nginx首页